### ISSUE TITLE
Tahoma API warning

### ISSUE THREAD

**Issue by Baptno** [nonolk/domoticz_tahoma_blind#14]
Hi, I recently installed your plugin to my Domoticz installation and it works pretty well, thanks a lot. I only have a problem, I received a mail from Somfy saying this :

> Warning on the way you use the TaHoma API
> 
> Dear customer,
>  
> In an ongoing effort to provide the best services to our users, we monitor the traffic generated by our applications and Smart Home boxes (TaHoma and Connexoon). It appears that you are using a third-party solution, either developed by yourself or provided by an external entity (developer or community of developers not working for Somfy). Such developments are made without our willingness and, sometimes, do not respect our usage guidelines.
> 
> We are contacting you today to update the way your script or your application behaves with our API as it is overconsuming our backend resources for your own installation. To do so, please contact the provider of your solution or update your code by October 31st.
> 
> We are asking all third-party scripts or application to reduce their polling activity on our API. In particular, the GET /setup endpoint is meant to be used once and only once by end-user session and not to regularly refresh the devices data.
> 
> As we do not want every TaHoma and Connexoon users be impacted by the overuse of some individuals, we will react in the coming months and set up rate limiters and automated bans if such changes are not applied.
> 
> Thank you for your understanding. 

Can you update your code to respect what they say in this mail ? Am I the only one who received it ?
Thanks a lot for your work !

**Comment by nonolk** [comment]
Hello,

Yes you are the only one, as far as I know. I will check if there is something I can adapt.

Bets regards,

**Comment by nonolk** [comment]
So first of all thank you for reporting this problem, as you are the only one who reported it for the plugin.

And now the good news, I'm testing right now a beta version which comply completely with Somfy's rules.

Stay tuned.

**Comment by nonolk** [comment]
Hello,

You can update to the latest beta version of the plugin by issuing the following command:
git clone -b Test https://github.com/nonolk/domoticz_tahoma_blind.git

This version comply with the latest somfy requirments.

**Comment by nonolk** [comment]
Closed with the new release of today.
