### ISSUE TITLE
Tahoma or conexoon IO blind plugin retrieve incorrect information

### ISSUE THREAD

**Issue by Turbo974** [nonolk/domoticz_tahoma_blind#16]
Hi,

Since updating to the last version of the plugin last week, when I try to closed a group of roller Shutters, the status of the roller Shutters is not correct. In the two with 2% and 1% should be at closed. It's  almost every time but not necessarly for the same evey time.
![image](https://user-images.githubusercontent.com/74417628/99085081-0f945b80-25c8-11eb-8283-2c78ab4ae868.png)
I did not have the issue previously with version 1.0.5 which was working pretty good for me.

I'm using a Debian on which the last stable Domoticz is installed and my Somfy roller shutters are managed through a Tahoma.

**Comment by nonolk** [comment]
Bonsoir,

Quelques questions:
- utilisez vous des groupes dans domoticz ?
- avez vous aussi me soucis en actionnant les volets un part un ?

Quand vous rencontrez le problème suivez cette procédure:
Logon here: with your login info (just fill in userid and Password)
https://tahomalink.com/enduser-mobile-web/enduserAPI/doc/test/3f0b5a478191e514cff8efbaf82545c2a2ce94d1b5b21347463261e6fbd88631

Then launch the following link:
https://tahomalink.com/enduser-mobile-web/enduserAPI/doc/test/706df574b0e21fd04e7e4325f2957c3cc678ae66d9d61e4e05985295f4a26f80

In the last link result search for your sun shade and provide the value of core:ClosureState and core:OpenClosedState

Et postez le résultat ici.

Cordialement

**Comment by Turbo974** [comment]
Bonjour,
Oui j'utilise des groupes dans Domoticz. Je crois que je n'ai testé qu'une fois de descendre un volet unitairement depuis suite quand je rencontre ce problème et de mémoire ça n'avait pas été très concluant mais je retesterai demain et ferez le reste de la procédure en même temps, là c'est pas trop possible avec les gamins qui dorment ^^

**Comment by Turbo974** [comment]
Ce matin j'ai eu un volet à 98% au lieu de 100% (et donc ouvert) le log en question : J'ai copié le log pour le volet en question ( Volet Ch Parents, Bureau plus bas dans le log n'est pas un volet et il est présent plus bas dans les log : 
{
    "creationTime": 1563538849000,
    "lastUpdateTime": 1563538849000,
    "label": "Volet Ch Parents",
    "deviceURL": "io://1217-5302-7796/10513926",
    "shortcut": false,
    "controllableName": "io:RollerShutterGenericIOComponent",
    "definition": {
      "commands": [
        {
          "commandName": "close",
          "nparams": 0
        },
        {
          "commandName": "delayedStopIdentify",
          "nparams": 1
        },
        {
          "commandName": "down",
          "nparams": 0
        },
        {
          "commandName": "getName",
          "nparams": 0
        },
        {
          "commandName": "identify",
          "nparams": 0
        },
        {
          "commandName": "my",
          "nparams": 0
        },
        {
          "commandName": "open",
          "nparams": 0
        },
        {
          "commandName": "refreshMemorized1Position",
          "nparams": 0
        },
        {
          "commandName": "setClosure",
          "nparams": 1
        },
        {
          "commandName": "setDeployment",
          "nparams": 1
        },
        {
          "commandName": "setMemorized1Position",
          "nparams": 1
        },
        {
          "commandName": "setName",
          "nparams": 1
        },
        {
          "commandName": "setPosition",
          "nparams": 1
        },
        {
          "commandName": "setSecuredPosition",
          "nparams": 1
        },
        {
          "commandName": "startIdentify",
          "nparams": 0
        },
        {
          "commandName": "stop",
          "nparams": 0
        },
        {
          "commandName": "stopIdentify",
          "nparams": 0
        },
        {
          "commandName": "up",
          "nparams": 0
        },
        {
          "commandName": "wink",
          "nparams": 1
        },
        {
          "commandName": "pairOneWayController",
          "nparams": 2
        },
        {
          "commandName": "unpairAllOneWayControllers",
          "nparams": 0
        },
        {
          "commandName": "unpairOneWayController",
          "nparams": 2
        }
      ],
      "states": [
        {
          "type": "ContinuousState",
          "qualifiedName": "core:ClosureState"
        },
        {
          "values": [
            "good",
            "low",
            "normal",
            "verylow"
          ],
          "type": "DiscreteState",
          "qualifiedName": "core:DiscreteRSSILevelState"
        },
        {
          "type": "ContinuousState",
          "qualifiedName": "core:Memorized1PositionState"
        },
        {
          "type": "DataState",
          "qualifiedName": "core:NameState"
        },
        {
          "values": [
            "closed",
            "open"
          ],
          "type": "DiscreteState",
          "qualifiedName": "core:OpenClosedState"
        },
        {
          "type": "ContinuousState",
          "qualifiedName": "core:PriorityLockTimerState"
        },
        {
          "type": "ContinuousState",
          "qualifiedName": "core:RSSILevelState"
        },
        {
          "type": "ContinuousState",
          "qualifiedName": "core:SecuredPositionState"
        },
        {
          "values": [
            "available",
            "unavailable"
          ],
          "type": "DiscreteState",
          "qualifiedName": "core:StatusState"
        },
        {
          "type": "ContinuousState",
          "qualifiedName": "core:TargetClosureState"
        },
        {
          "values": [
            "comfortLevel1",
            "comfortLevel2",
            "comfortLevel3",
            "comfortLevel4",
            "environmentProtection",
            "humanProtection",
            "userLevel1",
            "userLevel2"
          ],
          "type": "DiscreteState",
          "qualifiedName": "io:PriorityLockLevelState"
        },
        {
          "values": [
            "LSC",
            "SAAC",
            "SFC",
            "UPS",
            "externalGateway",
            "localUser",
            "myself",
            "rain",
            "security",
            "temperature",
            "timer",
            "user",
            "wind"
          ],
          "type": "DiscreteState",
          "qualifiedName": "io:PriorityLockOriginatorState"
        }
      ],
      "dataProperties": [
        {
          "value": "500",
          "qualifiedName": "core:identifyInterval"
        }
      ],
      "widgetName": "PositionableRollerShutter",
      "uiClass": "RollerShutter",
      "qualifiedName": "io:RollerShutterGenericIOComponent",
      "type": "ACTUATOR"
    },
    "states": [
      {
        "name": "core:NameState",
        "type": 3,
        "value": "Bureau"
      },
      {
        "name": "core:PriorityLockTimerState",
        "type": 1,
        "value": 0
      },
      {
        "name": "core:StatusState",
        "type": 3,
        "value": "available"
      },
      {
        "name": "core:DiscreteRSSILevelState",
        "type": 3,
        "value": "good"
      },
      {
        "name": "core:RSSILevelState",
        "type": 2,
        "value": 84
      },
      {
        "name": "core:ClosureState",
        "type": 1,
        "value": 0
      },
      {
        "name": "core:OpenClosedState",
        "type": 3,
        "value": "open"
      },
      {
        "name": "core:Memorized1PositionState",
        "type": 1,
        "value": 86
      },
      {
        "name": "core:TargetClosureState",
        "type": 1,
        "value": 0
      }
    ],
    "available": true,
    "enabled": true,
    "placeOID": "a57f05b2-3cb1-4cbc-842f-983ca07b3bac",
    "widget": "PositionableRollerShutter",
    "type": 1,
    "oid": "f8111369-d136-44b6-a43a-51637e00e0bb",
    "uiClass": "RollerShutter"
  },

**Comment by nonolk** [comment]
Bonjour, et vous n’avez pas d’Erreur dans les logs de domoticz ?
J’ai l´impression que je ne reçois pas l’information du 100% ou zéro.
Pouvez vous regarder dans le device domoticz vous avez la possibilité de voir des logs.
![AE7D74DB-B5AB-4166-A3D6-79195D2F6095](https://user-images.githubusercontent.com/26922736/99143585-e83c9d80-265e-11eb-91cc-068afcc23342.jpeg)


Ça permettra déjà de voir si la bonne info est reçue, peut être pas dans le bon ordre.

**Comment by Turbo974** [comment]
Dans les logs je vois que c'est mis à 98%, je ne comprends pas pourquoi :
2020-11-14 09:16:53 | Set Level: 98 %
Et en regardant les valeurs précédentes envoyés elles ne sont pas systèmatiquement identique : 
![image](https://user-images.githubusercontent.com/74417628/99143625-45385380-265f-11eb-97fc-8507da435ad2.png)

**Comment by nonolk** [comment]
En effet le plugin ne reçoit pas la valeur 0 ou la valeur 100 de l’api  somfy. Après la bonne question c’est pourquoi ?
Car d’après les logs on voit bien qu’elle est reçue mais pas tout le temps. Pouvez vous activer le debug au niveau du plugin on y verra peut être plus clair.´par contre il vous faudra dans tous les cas essayer de reproduire le soucis.
Pour voir les infos reçues.
Sinon je void donnerai une version de debug du plugin.

**Comment by Turbo974** [comment]
J'ai activé le mode debug et refait un test en me logguant au 2 liens postés plus haut. Dans le text log, je vois d'un volet posant problème cette fois : Set Level 2%
J'ai essayé de regardé les logs de domoticz même dans l'interface mais trop d'info sont envoyé par la Tahoma du coup je n'ai pas eu le temps de ne serait-ce que regarder. Je retesterai plus tard dans la journée mais en attendant les logs tirés des liens plus haut : 
{
    
  },

**Comment by Turbo974** [comment]
Je ne sais pas si ces logs suffiront mais j'ai ça, à la fin on voit le Volet Parent qui passe de 0 à 98 puis de 98 à 99 mais après ça je n'ai rien vu dans les logs d'équivalent :
2020-11-14 15:34:56.240 (Tahoma) Pushing 'DisconnectedEvent' on to queue
2020-11-14 15:34:56.256 (Tahoma) Processing 'DisconnectedEvent' message
2020-11-14 15:34:56.256 (Tahoma) Disconnect event received for 'tahomalink.com:443'.
2020-11-14 15:34:56.257 (Tahoma) Pushing 'onDisconnectCallback' on to queue
2020-11-14 15:34:56.257 (Tahoma) Processing 'onDisconnectCallback' message
2020-11-14 15:34:56.257 (Tahoma) Calling message handler 'onDisconnect'.
2020-11-14 15:35:01.297 (Tahoma) 73 70 6f 72 74 2d 53 65 63 75 72 69 74 79 3a 20 6d 61 78 2d s
2020-11-14 15:35:01.298 (Tahoma) Processing 'ReadEvent' message
2020-11-14 15:35:01.298 (Tahoma) Received 5 bytes of data
2020-11-14 15:35:01.298 (Tahoma) 30 0d 0a 0d 0a .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 0....
2020-11-14 15:35:01.298 (Tahoma) Pushing 'onMessageCallback' on to queue
2020-11-14 15:35:01.298 (Tahoma) Processing 'onMessageCallback' message
2020-11-14 15:35:01.298 (Tahoma) Calling message handler 'onMessage'.
2020-11-14 15:35:01.298 (Tahoma) Updating device:Volet Ch Dorian
2020-11-14 15:35:01.298 (Volet Ch Dorian) Updating device from 0:'0' to have values 2:'95'.
2020-11-14 15:35:01.309 (Tahoma) Updating device:Volet Ch Dorian
2020-11-14 15:35:01.309 (Volet Ch Dorian) Updating device from 2:'95' to have values 1:'100'.
2020-11-14 15:35:01.319 (Tahoma) Updating device:Volet Ch Parents
2020-11-14 15:35:01.319 (Volet Ch Parents) Updating device from 0:'0' to have values 2:'98'.
2020-11-14 15:35:01.330 (Tahoma) Updating device:Volet Ch Parents
2020-11-14 15:35:01.330 (Volet Ch Parents) Updating device from 2:'98' to have values 2:'99'.
2020-11-14 15:35:01.603 Status: OpenZWave: Received timeout notification from HomeID: 3849547065, NodeID: 15 (0x0f)
2020-11-14 15:35:06.256 (Tahoma) Queued asynchronous secure read aborted.
2020-11-14 15:35:06.256 (Tahoma) Pushing 'DisconnectedEvent' on to queue
2020-11-14 15:35:06.265 (Tahoma) Processing 'DisconnectedEvent' message
2020-11-14 15:35:06.265 (Tahoma) Disconnect event received for 'tahomalink.com:443'.
2020-11-14 15:35:06.265 (Tahoma) Pushing 'onDisconnectCallback' on to queue
2020-11-14 15:35:06.265 (Tahoma) Processing 'onDisconnectCallback' message
2020-11-14 15:35:06.265 (Tahoma) Calling message handler 'onDisconnect'.
2020-11-14 15:35:08.136 Status: OpenZWave: Received timeout notification from HomeID: 3849547065, NodeID: 15 (0x0f)
2020-11-14 15:35:11.308 (Tahoma) Received 5 bytes of data
2020-11-14 15:35:11.308 (Tahoma) 30 0d 0a 0d 0a .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. 0....
2020-11-14 15:35:11.308 (Tahoma) Pushing 'onMessageCallback' on to queue
2020-11-14 15:35:11.308 (Tahoma) Processing 'onMessageCallback' message
2020-11-14 15:35:11.308 (Tahoma) Calling message handler 'onMessage'.
2020-11-14 15:35:11.308 (Tahoma) []
2020-11-14 15:35:14.668 Status: OpenZWave: Received timeout notification from HomeID: 3849547065, NodeID: 15 (0x0f)
2020-11-14 15:35:16.268 (Tahoma) Queued asynchronous secure read aborted.
2020-11-14 15:35:16.268 (Tahoma) Pushing 'DisconnectedEvent' on to queue
2020-11-14 15:35:16.286 (Tahoma) Processing 'DisconnectedEvent' message
2020-11-14 15:35:16.286 (Tahoma) Disconnect event received for 'tahomalink.com:443'.
2020-11-14 15:35:16.286 (Tahoma) Pushing 'onDisconnectCallback' on to queue
2020-11-14 15:35:16.287 (Tahoma) Processing 'onDisconnectCallback' message
2020-11-14 15:35:16.287 (Tahoma) Calling message handler 'onDisconnect'.

**Comment by nonolk** [comment]
Merci pour les logs, qui m'on bien permit d'identifier le soucis:
_deviceURL":"io://xxxxx/xxxxx926","deviceStates":[
{"name":"core:ClosureState","type":1,"value":"1"},
{"name":"core:OpenClosedState","type":3,"value":"open"},
{"name":"core:ClosureState","type":1,"value":"0"},
{"name":"core:OpenClosedState","type":3,"value":"open"}],
"name":"DeviceStateChangedEvent"},_

On vois bien ici qu'il a y a deux fois la ligne ClosureState, ce qui est quelque chose de nouveau avant cela n'arrivait q'une fois par évenement.

Je vais adapter le code pour traiter cela.

Ps: Je me suis permis d'éditer vos logs pour cacher les informations trop personelles comme les devices urls.

**Comment by nonolk** [comment]
Pouvez vous metre  a jour le plugin, je viens de publier une version "corrective" mais comme je n'utilise plus ma connexoon , je ne peut pas la tester.

**Comment by Turbo974** [comment]
A priori c'est réglé, merci pour la réactivité ! Je ferme le ticket.
