### ISSUE TITLE
Error: (Somfy Tahoma) Exiting

### ISSUE THREAD

**Issue by Gerard-Oedzes** [nonolk/domoticz_tahoma_blind#2]
Goodmorning, 

Plugin is still working perfect, but get every day a view of these error's: 

2020-02-03 08:02:37.883 Error: (Somfy Tahoma) Exiting
2020-02-03 08:03:07.894 Error: (Somfy Tahoma) Exiting
2020-02-03 08:10:08.182 Error: (Somfy Tahoma) Exiting

Something i can do about it?

**Comment by nonolk** [comment]
Hello,

You can do nothing about it, it’s just because the tahoma website do not answer properly. 

Anyway, I’m still working on an updated version to solve the issue when adding new devices, which sometimes crash domoticz.

I will then handle this “error” in another way.

Best regards,

**Comment by nonolk** [comment]
Should be solved now.

**Comment by Gerard-Oedzes** [comment]
Thnx Nolok.. 

i removed the old version and installed new one... 
Domoticz dosnt chrash anymore when hardware is found! 

Manny thanx ( a happy user of this plugin :D )
