### ISSUE TITLE
Script modification for Awning

### ISSUE THREAD

**Issue by BG-Domoticz** [nonolk/domoticz_tahoma_blind#5]
Whow, you did a great job and it was so easy to implement to Domoticz!

I made a small adjustment to your plugin.py file so my awning could also be found and operated. Use it to your advantage.

Awnings, garage doors, screens, blinds, and windows things have the same notation as roller shutters.  Just use "awning", "garagedoor", "screen", "blind" or "window" instead of "rolleshutter" in thing definition.

Line in your script was:          
if ((device["uiClass"] == "RollerShutter") or (device["uiClass"] == "ExteriorScreen")):

Line in my script is now:
if ((device["uiClass"] == "RollerShutter") or (device["uiClass"] == "ExteriorScreen") or (device["uiClass"] == "Awning")):

**Comment by nonolk** [comment]
Hello,

Thank you for your input, I'm working on a new version, and I will include your info.

Best regards,

**Comment by nonolk** [comment]
My only problem is the available kind of devices in Domoticz see there:
https://www.domoticz.com/wiki/Developing_a_Python_plugin#Available_Device_Types

**Comment by nonolk** [comment]
Solved by version 1.0.4 who add support for several new type of devices, see on homepage for the complete list.
