### ISSUE TITLE
RTS - no return state issue

### ISSUE THREAD

**Issue by nlfva1** [nonolk/domoticz_tahoma_blind#6]
After installing the script I see the following error messages in the domoticz log:

Error: (Tahoma Rolluiken) 'onMessage' failed 'KeyError'.
Error: (Tahoma Rolluiken) ----> Line 283 in 'domoticz_tahoma_blind/plugin.py', function onMessage
Error: (Tahoma Rolluiken) ----> Line 176 in 'domoticz_tahoma_blind/plugin.py', function onMessage

I have SomfyIO and SomfyRTS using Tahoma box. Domoctiz 2020.2 and python version: 3.7.3 

Any idea's?

Regards,
Frank.

**Comment by nonolk** [comment]
Hello nlfva1,

It's probably coming from your res devices, because they do not have status indicator (I mean return state). As this is exactly with what the plugin is dealing on line 176. I'll will try to solve this issue for the next release (no ETA for now).

Maybe you can activate the debug of the plugin to see a bit more.

Best regards,

**Comment by nlfva1** [comment]
Hi,

Makes sense. Turned debug on and the error appears when processing the RTS devices, so in line with your expectation. 

Looking forward to the update, but no rush as in general the script is working fine.

One extra question. To close the blinds for 50% I use dzVents with "dz.devices('Tahoma Rolluiken - Rolluik 1').setLevel(50)". Is there an extra option you can specify to use the low speed ?

Regards,
Frank.

**Comment by nonolk** [comment]
Hello,

New version 1.0.5 should address this issue.
Please report back if this is the case or not.

Regards,

**Comment by nlfva1** [comment]
Will install and test the new version. Many thanks for the quick response.

**Comment by nlfva1** [comment]
Done testing and works perfectly.  Thank you very much.
