### ISSUE TITLE
Status not updating

### ISSUE THREAD

**Issue by pcdiks** [nonolk/domoticz_tahoma_blind#9]
I added the plugin to Domoticz and I see the new hardware in the list.
I can change the position of the cover without problems but after some time, the item on the switch page shows a value that does not corresponds with the actual setting. The following screen shot shows this but in reallity the slider should be at 60%:
![image](https://user-images.githubusercontent.com/16719277/85853907-9d0b1680-b7b3-11ea-8539-bea579c2cd52.png)

Also, the last update status stays on the date/time that the device was added to the hardware list. I think that should update more often like with the other switches.

I checked the logs and I see no problems. What can we do?

**Comment by nonolk** [comment]
Hello pcdiks,

It may come from a lot of reasons, but with nearly no info about your device (brand, kind, type). I can just guess, is this a RTS device ?

If this is an IO device, please provide all the needed information, domoticz version, plugin version and device information.

Best regards,

**Comment by pcdiks** [comment]
Hi,

It’s a somfy rts indeed and there is an app that I can use: Connexion
Domoticz version: 2020.02
Plug-in version: 1.0.5

Do you anything else?

**Comment by nonolk** [comment]
Hello,

So it’s just normal, rts blind do not provide status update as stated in the plugin definition. It means if you change the state externally of Domoticz it won’t be updated.

Best regards
